### ISSUE TITLE
problem building the distribution

### ISSUE THREAD

**Issue by compsagnathus** [nickcam/angular2-esri-netcore#1]
the gulp task dist:build does not exist.  Any suggestions?

**Comment by nickcam** [comment]
Hi - yeah you're right - it doesn't exist sorry, the gulp task is actually called `build:dist`. I've updated the readme to be correct. On that though - I've just made some big changes to this project and realised that the `build:dist` task is now failing at ngc compile time...well for me anyway. I'll look at fixing that sometime very soon.

**Comment by nickcam** [comment]
This is fixed now, turns out you have to use a version of typescript lower than 2.1.x for ngc to compile.
