### ISSUE TITLE
Types incompatible errors

### ISSUE THREAD

**Issue by Todane** [nickcam/angular2-esri-netcore#2]
Dear nickcam,

Thanks for this useful startup project.  When I built the project with Visual Studio 2017, I got many types incompatible errors.  

For example,  the codes in mapView.service.ts (line 24-29):

        this.view = new MapView({
            container: this.containerElementId,
            map: this._mapService.map,
            scale: 45700000, //default scale and center point
            center: [134, -24]
        });
cause this error: 
TS2345	Build:Argument of type '{ container: string; map: Map; scale: number; center: number[]; }' is not assignable to parameter of type 'MapViewProperties'.	

I go to the definition of MapView in the file node_modules/@types/arcgis-js-api/index.d.ts , and found the following type definitions:

 interface MapView extends View {
    center: Point;
    constraints: MapViewConstraints;
    extent: Extent;
    resizeAlign: string;
    rotation: number;
    scale: number;
    viewpoint: Viewpoint;
    zoom: number;

     //other functions omitted here    
  }

  interface MapViewConstructor {
    new(properties?: MapViewProperties): MapView;
  }

  export const MapView: MapViewConstructor;

  interface MapViewProperties extends ViewProperties {
    center?: PointProperties;
    constraints?: MapViewConstraints;
    extent?: ExtentProperties;
    resizeAlign?: string;
    rotation?: number;
    scale?: number;
    viewpoint?: ViewpointProperties;
    zoom?: number;
  }

It seems the codes to call ArcGIS for JavaScript is not compatible with the definition of the ArcGIS for JavaScript.  I'm new to TypeScript and ArcGIS for JavaScript.  Could you please shed some lights on how to fix those errors like this?  Thank you so much!

Tao

**Comment by nickcam** [comment]
Hi @Todane, this repo is a bit old now...well in terms of angular and .Net core versions it is. I wouldn't use it actually.

Have a look at esri loader [https://github.com/Esri/esri-loader](https://github.com/Esri/esri-loader) to see how to load arcgis js api into other frameworks.

I would also just use the .Net Core templates for an angular project that are in Visual Studio.  The latest ones use the angular cli and there's a nice separation between the .Net api and angular code.

Thanks,
Nick

**Comment by Todane** [comment]
Hi Nick,

Thank you so much for the suggestions.  I will try them.

Regards,

Tao
